variable "name" {
  description = "Name to be used on all the resources as identifier"
  default     = ""
}

variable "subnet_id"  {
    description = "Subnet ID for ENI - Generated by Subnet Module"
    default = ""
}

variable "tags" {
  description = "A map of tags to add to all resources"
  default     = {}
}