FROM ubuntu:bionic

ENV ANSIBLE_VERSION=2.6.4
ENV TERRAFORM_VERSION=0.11.10
RUN apt-get update -y && apt-get -y install curl gnupg2
RUN echo "deb https://rundeck.bintray.com/rundeck-deb /" | tee -a /etc/apt/sources.list.d/rundeck.list 
RUN curl 'https://bintray.com/user/downloadSubjectPublicKey?username=bintray' | apt-key add -
RUN apt-get update -y 
RUN apt-get install -y software-properties-common
RUN apt-get install -y \
    golang-go \
    python \
    curl \
    openjdk-8-jdk-headless \
    wget \
    uuid-runtime \
    unzip \
    openssh-client
RUN apt-get install -y \
    python-dev \
    python-pip \
    git-core \
    build-essential \
    libssl-dev \
    libffi-dev
RUN pip install --upgrade setuptools cffi
RUN pip install ansible==${ANSIBLE_VERSION} \
        pandevice \
        pan-python \
        xmltodict \
        awscli \
        azure-cli \
        paramiko \
        ipaddress \
        requests \
        requests-toolbelt \
        cryptography==2.4.2 \
        jsonschema
RUN pip install --upgrade pandevice
RUN go get "golang.org/x/crypto/ssh"
RUN ansible-galaxy install --force PaloAltoNetworks.paloaltonetworks
RUN curl https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip > terraform.zip
RUN unzip terraform.zip -d /bin/
RUN rm -f terraform.zip
RUN apt-get -y autoremove
RUN apt-get -y autoclean
RUN apt-get -y clean all
RUN rm -rf /root/.cache/pip
RUN rm -rf /root/.pip/cache
RUN rm -rf /var/lib/apt/lists/*
RUN rm -rf /var/cache/apt

ENV SERVER_URL=https://localhost:4443 \
    RUNDECK_STORAGE_PROVIDER=file \
    RUNDECK_PROJECT_STORAGE_TYPE=file \
    NO_LOCAL_MYSQL=false \
    LOGIN_MODULE=RDpropertyfilelogin \
    JAAS_CONF_FILE=jaas-loginmodule.conf \
    KEYSTORE_PASS=adminadmin \
    TRUSTSTORE_PASS=adminadmin \
    CLUSTER_MODE=false

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get -qq update && \
    apt-get -qqy install --no-install-recommends bash openjdk-8-jre-headless ca-certificates-java supervisor procps sudo ca-certificates openssh-client mysql-server mysql-client postgresql postgresql-client pwgen curl git uuid-runtime parallel jq && \
    cd /tmp/ && \
    curl -Lo /tmp/rundeck.deb https://dl.bintray.com/rundeck/rundeck-deb/rundeck_3.0.23.20190619-1.201906191858_all.deb && \
    echo 'df595816c4934e19c76da47ac89b7146856f6cc9099d60ca080d7c6b57bb3bcc  rundeck.deb' > /tmp/rundeck.sig && \
    shasum -a256 -c /tmp/rundeck.sig && \
    curl -Lo /tmp/rundeck-cli.deb https://github.com/rundeck/rundeck-cli/releases/download/v1.1.2/rundeck-cli_1.1.2-1_all.deb && \
    echo '43db7cf560a7f644c99f349f97203c28824249612da4129044cbb5ff37ecb2f7  rundeck-cli.deb' > /tmp/rundeck-cli.sig && \
    shasum -a256 -c /tmp/rundeck-cli.sig && \
    cd - && \
    dpkg -i /tmp/rundeck*.deb && rm /tmp/rundeck*.deb && \
    chown rundeck:rundeck /tmp/rundeck && \
    mkdir -p /var/lib/rundeck/.ssh && \
    chown rundeck:rundeck /var/lib/rundeck/.ssh && \
    sed -i "s/export RDECK_JVM=\"/export RDECK_JVM=\"\${RDECK_JVM} /" /etc/rundeck/profile && \
    curl -Lo /var/lib/rundeck/libext/rundeck-slack-incoming-webhook-plugin-0.6.jar https://github.com/higanworks/rundeck-slack-incoming-webhook-plugin/releases/download/v0.6.dev/rundeck-slack-incoming-webhook-plugin-0.6.jar && \
    echo 'd23b31ec4791dff1a7051f1f012725f20a1e3e9f85f64a874115e46df77e00b5  rundeck-slack-incoming-webhook-plugin-0.6.jar' > /tmp/rundeck-slack-plugin.sig && \
    cd /var/lib/rundeck/libext/ && \
    shasum -a256 -c /tmp/rundeck-slack-plugin.sig && \
    cd - && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
    
ADD content/ /
RUN chmod u+x /opt/run && \
    mkdir -p /var/log/supervisor && mkdir -p /opt/supervisor && \
    chmod u+x /opt/supervisor/rundeck && chmod u+x /opt/supervisor/mysql_supervisor && chmod u+x /opt/supervisor/fatalservicelistener


EXPOSE 4440 4443

VOLUME  ["/etc/rundeck", "/var/rundeck", "/var/lib/mysql", "/var/log/rundeck", "/opt/rundeck-plugins", "/var/lib/rundeck/logs", "/var/lib/rundeck/var/storage"]


ENTRYPOINT ["/opt/run"]
