variable "tags" {
  description = "A map of tags to add to all resources"
  default     = {}
}

variable "name" {
  description = "Name to be used on all the resources as identifier"
  default     = ""
}

variable "vpc_id"  {
    description = "VPC ID for spoke - Generated by VPC Module"
    default = ""
}

variable "cidr_blocks" {
  description = "List of IPv4 CIDR ranges to use on rule"
  type        = "list"
  default     = []
}

variable "type" {
  description = "Ingress or Egress Rule"
  type        = "list"
  default     = []
}
variable "from_port" {
  description = "Source Port for rule"
  type        = "list"  
  default     = []
}

variable "to_port" {
  description = "Destination Port for rule"
  type        = "list"  
  default     = []
}

variable "protocol" {
  description = "tcp, udp, icmp, -1 for any"
  default     = []
}

variable "rule_name" {
  description = "Used for description field on each rule within SG"
  default     = []
}
