

variable "vpc_id"  {
    description = "VPC ID for spoke - Generated by VPC Module"
    default = ""
}

variable "route_table_id"  {
    description = "ID of Route Table to attach subnets - Generated by route_table Module"
    default = ""
}

variable "subnets" {
  description = "A list of subnets to create inside the VPC"
  default     = []
}

variable "subnet_names" {
  description = "A list of names for subnets inside the VPC"
  default     = []
}