variable "name" {
  description = "Name tag for subnet"
  default     = ""
}

variable "tags" {
  description = "A map of tags to add to all resources"
  default     = {}
}

variable "vpc_id"  {
    description = "VPC ID for spoke - Generated by VPC Module"
    default = ""
}

variable "route_table_id"  {
    description = "ID of Route Table to attach subnets - Generated by route_table Module"
    default = ""
}

variable "cidr_block" {
  description = "CIDR of Subnet to create"
  default     = ""
}

variable "availability_zone" {
  description = "CIDR of Subnet to create"
  default     = ""
}