variable "vpc_id"  {
    description = "VPC ID for spoke - Generated by VPC Module"
    default = ""
}

variable "name" {
  description = "Name to be used on all the resources as identifier"
  default     = ""
}

variable "default_igw" {
  description = "Option for adding default route to IGW"
  default     = ""
}

variable "default_vgw" {
  description = "Option for adding default route to VGW"
  default     = ""
}

variable "default_tgw" {
  description = "Option for adding default route to TGW"
  default     = ""
}

variable "default_eni" {
  description = "Option for adding default route to ENI"
  default     = ""
}